export const CLIENTS_DATA = [
  {
    id: 1,
    name: "Tech Solutions Inc",
    email: "contact@techsolutions.com",
    contactPerson: "James Wilson",
    company: "Tech Solutions Inc",
    status: "Active",
    joinDate: "2024-01-10",
    phone: "+1-234-567-8900",
    projects: 5,
  },
  {
    id: 2,
    name: "BuildRight Corp",
    email: "info@buildright.com",
    contactPerson: "Sarah Anderson",
    company: "BuildRight Corp",
    status: "Active",
    joinDate: "2024-02-15",
    phone: "+1-234-567-8901",
    projects: 3,
  },
  {
    id: 3,
    name: "Urban Developers",
    email: "hello@urbandevelopers.com",
    contactPerson: "Michael Chen",
    company: "Urban Developers",
    status: "Active",
    joinDate: "2024-03-20",
    phone: "+1-234-567-8902",
    projects: 8,
  },
  {
    id: 4,
    name: "Green Constructions",
    email: "support@greencon.com",
    contactPerson: "Emily Roberts",
    company: "Green Constructions",
    status: "Inactive",
    joinDate: "2024-01-05",
    phone: "+1-234-567-8903",
    projects: 2,
  },
  {
    id: 5,
    name: "Premier Building Group",
    email: "admin@premierbuild.com",
    contactPerson: "David Martinez",
    company: "Premier Building Group",
    status: "Active",
    joinDate: "2024-02-28",
    phone: "+1-234-567-8904",
    projects: 6,
  },
];

export const CLIENT_STATUS = [
  { label: "Active", value: "Active" },
  { label: "Inactive", value: "Inactive" },
  { label: "Suspended", value: "Suspended" },
];
