export const cancelProjectsData = [
  {
    id: 1,
    name: "John Smith",
    project: "Shopping Mall Renovation",
    bid: "$2,350,000",
    timeline: "8 months",
    status: "Pending Cancellation",
    reason: "Budget constraints",
    requestDate: "2024-01-15",
  },
  {
    id: 2,
    name: "James Brown",
    project: "Office Complex Construction",
    bid: "$2,500,000",
    timeline: "7 months",
    status: "Approved for Cancellation",
    reason: "Schedule conflict",
    requestDate: "2024-01-10",
  },
  {
    id: 3,
    name: "Ahmed Khan",
    project: "Residential Building",
    bid: "$3,200,000",
    timeline: "10 months",
    status: "Under Review",
    reason: "Client request",
    requestDate: "2024-01-20",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    project: "Shopping Mall Renovation",
    bid: "$1,800,000",
    timeline: "6 months",
    status: "Cancelled",
    reason: "Project completed",
    requestDate: "2024-01-05",
  },
  {
    id: 5,
    name: "Mike Johnson",
    project: "Grey Structure Build",
    bid: "$2,750,000",
    timeline: "9 months",
    status: "Rejected Cancellation",
    reason: "Work in progress",
    requestDate: "2024-01-22",
  },
]
