export const cancelProjectsData = [
  {
    id: 1,
    name: "John Smith",
    project: "Shopping Mall Renovation - Project 1",
    bid: "$2,350,000",
    bidAmount: 2350000,
    timeline: "8 months",
    status: "Pending Cancellation",
    reason: "Budget constraints",
    requestDate: "2025-11-20",
  },
  {
    id: 2,
    name: "James Brown",
    project: "Shopping Mall Renovation - Project 2",
    bid: "$2,500,000",
    bidAmount: 2500000,
    timeline: "7 months",
    status: "Approved for Cancellation",
    reason: "Schedule conflict",
    requestDate: "2025-11-18",
  },
  {
    id: 3,
    name: "Ahmed Khan",
    project: "Office Complex Construction - Project 3",
    bid: "$3,200,000",
    bidAmount: 3200000,
    timeline: "10 months",
    status: "Under Review",
    reason: "Resource unavailability",
    requestDate: "2025-11-22",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    project: "Residential Building - Project 4",
    bid: "$1,800,000",
    bidAmount: 1800000,
    timeline: "6 months",
    status: "Cancelled",
    reason: "Client request",
    requestDate: "2025-11-15",
  },
  {
    id: 5,
    name: "Mike Johnson",
    project: "Shopping Mall Renovation - Project 5",
    bid: "$2,750,000",
    bidAmount: 2750000,
    timeline: "9 months",
    status: "Rejected Cancellation",
    reason: "Legal implications",
    requestDate: "2025-11-19",
  },
  {
    id: 6,
    name: "Emma Davis",
    project: "Bridge Construction - Project 6",
    bid: "$4,100,000",
    bidAmount: 4100000,
    timeline: "12 months",
    status: "Pending Cancellation",
    reason: "Environmental concerns",
    requestDate: "2025-11-23",
  },
  {
    id: 7,
    name: "David Lee",
    project: "Hospital Expansion - Project 7",
    bid: "$3,500,000",
    bidAmount: 3500000,
    timeline: "11 months",
    status: "Under Review",
    reason: "Contractor withdrawal",
    requestDate: "2025-11-21",
  },
  {
    id: 8,
    name: "Lisa Anderson",
    project: "Downtown Plaza Renovation - Project 8",
    bid: "$2,800,000",
    bidAmount: 2800000,
    timeline: "9 months",
    status: "Approved for Cancellation",
    reason: "Permit delays",
    requestDate: "2025-11-17",
  },
];
